// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wefakzffrxgqpjquuhsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlZmFremZmcnhncXBqcXV1aHNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxODkwMzYsImV4cCI6MjA1ODc2NTAzNn0.oAkbuT9O0fwAptzFVTi2nF07kyokEfroHp2i4hMN9iI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);